# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

controllers:
    resource: '../src/Controller'
    type: attribute
    prefix: /api

api_login_check:
    path: /api/login_check